//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common.Host {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.Host.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component &apos;{0}&apos; is not running.
        /// </summary>
        public static string E_ITA_COMPONENT_NOT_RUNNING {
            get {
                return ResourceManager.GetString("E_ITA_COMPONENT_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not found in component &apos;{1}&apos;..
        /// </summary>
        public static string E_ITA_COMPONENT_PROPERTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("E_ITA_COMPONENT_PROPERTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error has occurred.
        /// </summary>
        public static string E_ITA_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading settings from &apos;{0}&apos;..
        /// </summary>
        public static string E_ITA_LOAD_FILE_STORAGE_SETTINGS {
            get {
                return ResourceManager.GetString("E_ITA_LOAD_FILE_STORAGE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory configuration parameter &apos;{1}&apos; for component &apos;{0}&apos; is absent.
        /// </summary>
        public static string E_ITA_NO_CONFIG_PARAMETER {
            get {
                return ResourceManager.GetString("E_ITA_NO_CONFIG_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred while reading configuration parameter &apos;{1}&apos; of component &apos;{0}&apos;.
        /// </summary>
        public static string E_ITA_READCONFIGURATION {
            get {
                return ResourceManager.GetString("E_ITA_READCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving settings to &apos;{0}&apos;..
        /// </summary>
        public static string E_ITA_SAVE_FILE_STORAGE_SETTINGS {
            get {
                return ResourceManager.GetString("E_ITA_SAVE_FILE_STORAGE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred while writing configuration parameter &apos;{1}&apos; of component &apos;{0}&apos;.
        /// </summary>
        public static string E_ITA_WRITECONFIGURATION {
            get {
                return ResourceManager.GetString("E_ITA_WRITECONFIGURATION", resourceCulture);
            }
        }
    }
}
