//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string E_ITA_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyzабвгдеёжзиклмнопрстуфхцчшщьыъэюя.
        /// </summary>
        public static string I_ITA_COMMON_ABC_LOWER {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_ABC_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZАБВГДЕЁЖЗИКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯ.
        /// </summary>
        public static string I_ITA_COMMON_ABC_UPPER {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_ABC_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string I_ITA_COMMON_ABORT {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string I_ITA_COMMON_CANCEL {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Description error&gt;: {0}.
        /// </summary>
        public static string I_ITA_COMMON_ERROR_DESCR {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_ERROR_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Information:
        ///.
        /// </summary>
        public static string I_ITA_COMMON_EXCEPTION {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string I_ITA_COMMON_HIDE_DETAILS {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_HIDE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string I_ITA_COMMON_IGNORE {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Message: {1}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_MESSAGE {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Method:     {4}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_METHOD {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string I_ITA_COMMON_NO {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        public static string I_ITA_COMMON_NONE {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string I_ITA_COMMON_OK {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Parameters: {5}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_PARAMS {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string I_ITA_COMMON_RETRY {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string I_ITA_COMMON_SHOW_DETAILS {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_SHOW_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Source:  {3}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_SOURCE {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Stack trace:
        ///{6}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_STACKTRACE {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_STACKTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Type:       {0}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_TYPE {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Hyperlink:    {2}
        ///.
        /// </summary>
        public static string I_ITA_COMMON_URL {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string I_ITA_COMMON_YES {
            get {
                return ResourceManager.GetString("I_ITA_COMMON_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on resuming.
        /// </summary>
        public static string I_ITA_ERROR_ON_CONTINUE {
            get {
                return ResourceManager.GetString("I_ITA_ERROR_ON_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on initialization.
        /// </summary>
        public static string I_ITA_ERROR_ON_INIT {
            get {
                return ResourceManager.GetString("I_ITA_ERROR_ON_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on pausing.
        /// </summary>
        public static string I_ITA_ERROR_ON_PAUSE {
            get {
                return ResourceManager.GetString("I_ITA_ERROR_ON_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on startup.
        /// </summary>
        public static string I_ITA_ERROR_ON_START {
            get {
                return ResourceManager.GetString("I_ITA_ERROR_ON_START", resourceCulture);
            }
        }
    }
}
