//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common.ETWTest.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.ETWTest.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Method=&apos;{0}&apos; {1}.
        /// </summary>
        internal static string event_Fail {
            get {
                return ResourceManager.GetString("event_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic error event. Method=&apos;{0}&apos; {1}.
        /// </summary>
        internal static string event_FireEventError {
            get {
                return ResourceManager.GetString("event_FireEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic information event. Method=&apos;{0}&apos; {1}.
        /// </summary>
        internal static string event_FireEventInfo {
            get {
                return ResourceManager.GetString("event_FireEventInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic verbose event. Method=&apos;{0}&apos; {1}.
        /// </summary>
        internal static string event_FireEventVerbose {
            get {
                return ResourceManager.GetString("event_FireEventVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load CPU duration &apos;{0}&apos; seconds.
        /// </summary>
        internal static string event_LoadCpu {
            get {
                return ResourceManager.GetString("event_LoadCpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method=&apos;{0}&apos; {1}.
        /// </summary>
        internal static string event_Start {
            get {
                return ResourceManager.GetString("event_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method=&apos;{0}&apos; {1}.
        /// </summary>
        internal static string event_Stop {
            get {
                return ResourceManager.GetString("event_Stop", resourceCulture);
            }
        }
    }
}
