//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common.Host.MonitoringEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MonitoringEngine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonitoringEngine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.Host.MonitoringEngine.MonitoringEngine", typeof(MonitoringEngine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_EventLog_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_EventLog.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_EventLog_Location {
            get {
                object obj = ResourceManager.GetObject("m_EventLog.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_EventLog_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_EventLog.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_AddRequestTime_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_AddRequestTime.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=355,Y=94}.
        /// </summary>
        public static System.Drawing.Point m_PC_AddRequestTime_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_AddRequestTime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_AddRequestTime_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_AddRequestTime.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_DBSize_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_DBSize.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=116,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_PC_DBSize_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_DBSize.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_DBSize_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_DBSize.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_DeleteRequestTime_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_DeleteRequestTime.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=171}.
        /// </summary>
        public static System.Drawing.Point m_PC_DeleteRequestTime_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_DeleteRequestTime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_DeleteRequestTime_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_DeleteRequestTime.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_EnrollRequestTime_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_EnrollRequestTime.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=186,Y=94}.
        /// </summary>
        public static System.Drawing.Point m_PC_EnrollRequestTime_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_EnrollRequestTime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_EnrollRequestTime_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_EnrollRequestTime.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_IdentifyRequestTime_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_IdentifyRequestTime.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=372,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_PC_IdentifyRequestTime_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_IdentifyRequestTime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_IdentifyRequestTime_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_IdentifyRequestTime.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_RequestsNum_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_RequestsNum.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=227,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_PC_RequestsNum_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_RequestsNum.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_RequestsNum_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_RequestsNum.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_UpdateRequestTime_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_UpdateRequestTime.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=190,Y=171}.
        /// </summary>
        public static System.Drawing.Point m_PC_UpdateRequestTime_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_UpdateRequestTime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_UpdateRequestTime_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_UpdateRequestTime.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_VerifyRequestTime_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_VerifyRequestTime.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=94}.
        /// </summary>
        public static System.Drawing.Point m_PC_VerifyRequestTime_Location {
            get {
                object obj = ResourceManager.GetObject("m_PC_VerifyRequestTime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Private.
        /// </summary>
        public static System.CodeDom.MemberAttributes m_PC_VerifyRequestTime_Modifiers {
            get {
                object obj = ResourceManager.GetObject("m_PC_VerifyRequestTime.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
