//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Wizards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Wizards.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating database..
        /// </summary>
        public static string E_DBWIZARD_DATABASE_SETUP_FAILED {
            get {
                return ResourceManager.GetString("E_DBWIZARD_DATABASE_SETUP_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard database connection settings internal error..
        /// </summary>
        public static string E_DBWIZARD_ERROR {
            get {
                return ResourceManager.GetString("E_DBWIZARD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve list of databases and users from a database server..
        /// </summary>
        public static string E_DBWIZARD_LIST_DB_ERROR {
            get {
                return ResourceManager.GetString("E_DBWIZARD_LIST_DB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting list of available database servers..
        /// </summary>
        public static string E_DBWIZARD_LIST_SERVERS {
            get {
                return ResourceManager.GetString("E_DBWIZARD_LIST_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is unavailable or has unsupported version.
        /// </summary>
        public static string E_ITA_DATABASE_IS_UNAVAILABLE {
            get {
                return ResourceManager.GetString("E_ITA_DATABASE_IS_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while looking up the user&apos;s SID.
        /// </summary>
        public static string E_ITA_DATABASE_UNKNOWN_USER {
            get {
                return ResourceManager.GetString("E_ITA_DATABASE_UNKNOWN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while determining the type of database server.
        /// </summary>
        public static string E_ITA_DATABASE_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("E_ITA_DATABASE_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while validating the database.
        /// </summary>
        public static string E_ITA_DATABASE_VERSION_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_DATABASE_VERSION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current database version {0} is not supported by the server. The required version is {1}..
        /// </summary>
        public static string E_ITA_DB_HAS_OLD_VERSION {
            get {
                return ResourceManager.GetString("E_ITA_DB_HAS_OLD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string E_ITA_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed with errors.
        /// </summary>
        public static string E_ITA_FINISHED_WITH_ERRORS {
            get {
                return ResourceManager.GetString("E_ITA_FINISHED_WITH_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error when upgrading a database..
        /// </summary>
        public static string E_ITA_INITIAL_WIZARD_DATABASE_UPDATE_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_INITIAL_WIZARD_DATABASE_UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the event log..
        /// </summary>
        public static string E_ITA_OPEN_EVENTLOG {
            get {
                return ResourceManager.GetString("E_ITA_OPEN_EVENTLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string E_ITA_UNHANDLED_EXCEPTION {
            get {
                return ResourceManager.GetString("E_ITA_UNHANDLED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error when upgrading a database..
        /// </summary>
        public static string E_ITA_UPDATE_FATAL_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_FATAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the version of the database. The database has an incorrect structure..
        /// </summary>
        public static string E_ITA_UPDATE_INVALID_DATABASE {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_INVALID_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the database upgrade script resource..
        /// </summary>
        public static string E_ITA_UPDATE_INVALID_SCRIPT {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_INVALID_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not implement interface ICustomUpdateStep..
        /// </summary>
        public static string E_ITA_UPDATE_NO_CUSTOM_STEP {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_NO_CUSTOM_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version {0} cannot be updated. The minimum supported version is {1}..
        /// </summary>
        public static string E_ITA_UPDATE_OLD_VERSION {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_OLD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the version of the database..
        /// </summary>
        public static string E_ITA_UPDATE_UNKNOWN_VERSION {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_UNKNOWN_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type of update activity..
        /// </summary>
        public static string E_ITA_UPDATE_UNSUPPORTED_ACTION {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_UNSUPPORTED_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading your current version of the database is not supported..
        /// </summary>
        public static string E_ITA_UPDATE_UNSUPPORTED_VERSION {
            get {
                return ResourceManager.GetString("E_ITA_UPDATE_UNSUPPORTED_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User rights validation error.
        /// </summary>
        public static string E_ITA_USER_ACCESS_ERROR {
            get {
                return ResourceManager.GetString("E_ITA_USER_ACCESS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard helps you configure a connection to a new or existing database server..
        /// </summary>
        public static string I_ITA_DATABASE_INFO {
            get {
                return ResourceManager.GetString("I_ITA_DATABASE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is up-to-date.
        /// </summary>
        public static string I_ITA_DATABASE_IS_ACTUAL {
            get {
                return ResourceManager.GetString("I_ITA_DATABASE_IS_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must upgrade the database.
        /// </summary>
        public static string I_ITA_DATABASE_IS_NOT_ACTUAL {
            get {
                return ResourceManager.GetString("I_ITA_DATABASE_IS_NOT_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the database connection Wizard.
        /// </summary>
        public static string I_ITA_DATABASE_WELCOME {
            get {
                return ResourceManager.GetString("I_ITA_DATABASE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed.
        /// </summary>
        public static string I_ITA_FINISHED {
            get {
                return ResourceManager.GetString("I_ITA_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the result ....
        /// </summary>
        public static string I_ITA_RESULT_WAIT {
            get {
                return ResourceManager.GetString("I_ITA_RESULT_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Wizard will restart the management server. Do you Want To Continue?.
        /// </summary>
        public static string I_ITA_SERVER_RESTART_WARNING {
            get {
                return ResourceManager.GetString("I_ITA_SERVER_RESTART_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string I_ITA_THANKS {
            get {
                return ResourceManager.GetString("I_ITA_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is running..
        /// </summary>
        public static string I_SERVER_STATUS_RUNNING_BALLOON {
            get {
                return ResourceManager.GetString("I_SERVER_STATUS_RUNNING_BALLOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Oracle Data Provider for .NET.
        ///It is either not installed or not properly configured..
        /// </summary>
        public static string IDS_WIZ_SRV_ORACLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_WIZ_SRV_ORACLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string WIZ_ACTION {
            get {
                return ResourceManager.GetString("WIZ_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the Active Directory container object.
        /// </summary>
        public static string WIZ_AD_SELECT_CONTAINER {
            get {
                return ResourceManager.GetString("WIZ_AD_SELECT_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is not defined.
        /// </summary>
        public static string WIZ_AD_SID_IS_NULL {
            get {
                return ResourceManager.GetString("WIZ_AD_SID_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user {0} does not belong to the specified container {1}. Select a different container objects.
        /// </summary>
        public static string WIZ_AD_SID_NOT_FOUND {
            get {
                return ResourceManager.GetString("WIZ_AD_SID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automode is completed..
        /// </summary>
        public static string WIZ_AUTO_MODE_COMPLETED {
            get {
                return ResourceManager.GetString("WIZ_AUTO_MODE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of automode:.
        /// </summary>
        public static string WIZ_AUTO_MODE_ERROR {
            get {
                return ResourceManager.GetString("WIZ_AUTO_MODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred reading initialization parameters:.
        /// </summary>
        public static string WIZ_AUTO_MODE_INIT_ERROR {
            get {
                return ResourceManager.GetString("WIZ_AUTO_MODE_INIT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automode is  launched ....
        /// </summary>
        public static string WIZ_AUTO_MODE_STARTED {
            get {
                return ResourceManager.GetString("WIZ_AUTO_MODE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL.
        /// </summary>
        public static string WIZ_AZURE_SQL {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Test connection.
        /// </summary>
        public static string WIZ_AZURE_SQL_CHECK_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_CHECK_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string WIZ_AZURE_SQL_CONNECTING {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Azure SQL.
        /// </summary>
        public static string WIZ_AZURE_SQL_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create a new user.
        /// </summary>
        public static string WIZ_AZURE_SQL_CREATE_NEW_USER {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_CREATE_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database credentials type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string WIZ_AZURE_SQL_CREDENTIAL_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_CREDENTIAL_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database contains data. New database creation is denied..
        /// </summary>
        public static string WIZ_AZURE_SQL_DENY_FOR_DB_CREATION {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_DENY_FOR_DB_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name:.
        /// </summary>
        public static string WIZ_AZURE_SQL_ENTER_DB_NAME {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_ENTER_DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name:.
        /// </summary>
        public static string WIZ_AZURE_SQL_ENTER_SERVER_NAME {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_ENTER_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SID of the database:.
        /// </summary>
        public static string WIZ_AZURE_SQL_ENTER_SID {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_ENTER_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string WIZ_AZURE_SQL_NEED_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_NEED_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string WIZ_AZURE_SQL_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not specified.
        /// </summary>
        public static string WIZ_AZURE_SQL_PASSWORD_IS_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_PASSWORD_IS_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database scheme.
        /// </summary>
        public static string WIZ_AZURE_SQL_SELECT_SCHEME {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_SELECT_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Azure SQL server and specify connection parameters for the administrator.
        /// </summary>
        public static string WIZ_AZURE_SQL_SELECT_SERVER {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_SELECT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the user settings that will be used to connect to the database.
        /// </summary>
        public static string WIZ_AZURE_SQL_SELECT_USER_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_SELECT_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the name of the database schema: .
        /// </summary>
        public static string WIZ_AZURE_SQL_SET_SCHEME_NAME {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_SET_SCHEME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User supplied parameters will be used for server connection and will be assigned to the selected database.
        /// </summary>
        public static string WIZ_AZURE_SQL_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User name:.
        /// </summary>
        public static string WIZ_AZURE_SQL_USER_NAME {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string WIZ_AZURE_SQL_USER_NAME_LABEL {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_USER_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string WIZ_AZURE_SQL_USER_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_AZURE_SQL_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up a database.
        /// </summary>
        public static string WIZ_BACKUP {
            get {
                return ResourceManager.GetString("WIZ_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that before updating the database
        ///has been backed up.
        /// </summary>
        public static string WIZ_BACKUP_CONFIRM {
            get {
                return ResourceManager.GetString("WIZ_BACKUP_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-connect to a database.
        /// </summary>
        public static string WIZ_CAPTION_CONNECT {
            get {
                return ResourceManager.GetString("WIZ_CAPTION_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-create a database.
        /// </summary>
        public static string WIZ_CAPTION_CREATE {
            get {
                return ResourceManager.GetString("WIZ_CAPTION_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard has collected all the necessary information to configure the database. Click &quot;next&quot; to start the process or the &quot;back&quot; to return to the settings..
        /// </summary>
        public static string WIZ_CLICK_NEXT {
            get {
                return ResourceManager.GetString("WIZ_CLICK_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization parameters contain errors:.
        /// </summary>
        public static string WIZ_CONFIG_PARAMETERS_HAVE_ERRORS {
            get {
                return ResourceManager.GetString("WIZ_CONFIG_PARAMETERS_HAVE_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking current configuration.
        /// </summary>
        public static string WIZ_CONFIG_VALIDATION {
            get {
                return ResourceManager.GetString("WIZ_CONFIG_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select configuration.
        /// </summary>
        public static string WIZ_CONFIGURATION_SELECTING {
            get {
                return ResourceManager.GetString("WIZ_CONFIGURATION_SELECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that a backup copy is relevant.
        /// </summary>
        public static string WIZ_CONFIRM_BACKUP_IS_ACTUAL {
            get {
                return ResourceManager.GetString("WIZ_CONFIRM_BACKUP_IS_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to existing database.
        /// </summary>
        public static string WIZ_CONNECT_TO_DB_MODE {
            get {
                return ResourceManager.GetString("WIZ_CONNECT_TO_DB_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to an existing DATABASE.
        /// </summary>
        public static string WIZ_CONNECT_TO_EXISTING_DB {
            get {
                return ResourceManager.GetString("WIZ_CONNECT_TO_EXISTING_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection settings.
        /// </summary>
        public static string WIZ_CONNECTION_PARAMETERS {
            get {
                return ResourceManager.GetString("WIZ_CONNECTION_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new configuration.
        /// </summary>
        public static string WIZ_CREATE_NEW_CONFIG {
            get {
                return ResourceManager.GetString("WIZ_CREATE_NEW_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new DATABASE.
        /// </summary>
        public static string WIZ_CREATE_NEW_DB {
            get {
                return ResourceManager.GetString("WIZ_CREATE_NEW_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new database &amp;.
        /// </summary>
        public static string WIZ_CREATE_NEW_DB_MODE {
            get {
                return ResourceManager.GetString("WIZ_CREATE_NEW_DB_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You create and configure the server database..
        /// </summary>
        public static string WIZ_CREATING_AND_CONFIGURATING {
            get {
                return ResourceManager.GetString("WIZ_CREATING_AND_CONFIGURATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database {0} already exists. Enter a different name.
        /// </summary>
        public static string WIZ_DB_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("WIZ_DB_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a database.
        /// </summary>
        public static string WIZ_DB_CREATING {
            get {
                return ResourceManager.GetString("WIZ_DB_CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the current database:.
        /// </summary>
        public static string WIZ_DB_CURRENT_NAME {
            get {
                return ResourceManager.GetString("WIZ_DB_CURRENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database does not need to be upgrated..
        /// </summary>
        public static string WIZ_DB_DOESNT_NEED_UPDATE {
            get {
                return ResourceManager.GetString("WIZ_DB_DOESNT_NEED_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name not specified.
        /// </summary>
        public static string WIZ_DB_ENTER_DB {
            get {
                return ResourceManager.GetString("WIZ_DB_ENTER_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least 8 and not more than 80 characters.
        /// </summary>
        public static string WIZ_DB_ENTER_EXISTS_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_DB_ENTER_EXISTS_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least 8 and not more than 80 characters, and also contain uppercase/lowercase letters and numbers.
        /// </summary>
        public static string WIZ_DB_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_DB_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login is not specified.
        /// </summary>
        public static string WIZ_DB_ENTER_USER {
            get {
                return ResourceManager.GetString("WIZ_DB_ENTER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while granting rights to the current user to have access to an existing database. After Setup completes, you must configure the service access to the database manually, or restart the wizard database connection under a user account with rights of securityadmin..
        /// </summary>
        public static string WIZ_DB_GRANT_PERMISSION_ERROR {
            get {
                return ResourceManager.GetString("WIZ_DB_GRANT_PERMISSION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid characters: A-Z, a-z, 0-9 and _.
        /// </summary>
        public static string WIZ_DB_INVALID_DATABASE_NAME {
            get {
                return ResourceManager.GetString("WIZ_DB_INVALID_DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database name. In the name of the only characters, numbers and underscores.
        /// </summary>
        public static string WIZ_DB_INVALID_DATABASE_NAME_EXT {
            get {
                return ResourceManager.GetString("WIZ_DB_INVALID_DATABASE_NAME_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid characters: A-Z, a-z, 0-9 and _.
        /// </summary>
        public static string WIZ_DB_INVALID_LOGIN {
            get {
                return ResourceManager.GetString("WIZ_DB_INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user login. The name can contain only characters, numbers and underscores.
        /// </summary>
        public static string WIZ_DB_INVALID_LOGIN_EXT {
            get {
                return ResourceManager.GetString("WIZ_DB_INVALID_LOGIN_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was successfully updated.
        /// </summary>
        public static string WIZ_DB_IS_UPDATED {
            get {
                return ResourceManager.GetString("WIZ_DB_IS_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was successfully updated to version:.
        /// </summary>
        public static string WIZ_DB_IS_UPDATED_TO_VERSION {
            get {
                return ResourceManager.GetString("WIZ_DB_IS_UPDATED_TO_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login DB:.
        /// </summary>
        public static string WIZ_DB_LOGIN {
            get {
                return ResourceManager.GetString("WIZ_DB_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the DATABASE {0} user {1}..
        /// </summary>
        public static string WIZ_DB_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("WIZ_DB_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name:.
        /// </summary>
        public static string WIZ_DB_NAME {
            get {
                return ResourceManager.GetString("WIZ_DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue the server configuration the selected database needs to be updated to the next version:.
        /// </summary>
        public static string WIZ_DB_NEED_TO_BE_UPDATED {
            get {
                return ResourceManager.GetString("WIZ_DB_NEED_TO_BE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must include numbers.
        /// </summary>
        public static string WIZ_DB_PASSWORD_NO_DIGIT {
            get {
                return ResourceManager.GetString("WIZ_DB_PASSWORD_NO_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain characters in lowercase.
        /// </summary>
        public static string WIZ_DB_PASSWORD_NO_LOWER {
            get {
                return ResourceManager.GetString("WIZ_DB_PASSWORD_NO_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain special characters.
        /// </summary>
        public static string WIZ_DB_PASSWORD_NO_SPECIAL {
            get {
                return ResourceManager.GetString("WIZ_DB_PASSWORD_NO_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain uppercase characters.
        /// </summary>
        public static string WIZ_DB_PASSWORD_NO_UPPER {
            get {
                return ResourceManager.GetString("WIZ_DB_PASSWORD_NO_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must not contain more than {0} characters.
        /// </summary>
        public static string WIZ_DB_PASSWORD_TOO_LONG {
            get {
                return ResourceManager.GetString("WIZ_DB_PASSWORD_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least {0} characters.
        /// </summary>
        public static string WIZ_DB_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("WIZ_DB_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database provider.
        /// </summary>
        public static string WIZ_DB_PROVIDER {
            get {
                return ResourceManager.GetString("WIZ_DB_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match.
        /// </summary>
        public static string WIZ_DB_RECONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_DB_RECONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database is selected..
        /// </summary>
        public static string WIZ_DB_SELECT_DB {
            get {
                return ResourceManager.GetString("WIZ_DB_SELECT_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database wizard.
        /// </summary>
        public static string WIZ_DB_TITLE {
            get {
                return ResourceManager.GetString("WIZ_DB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the database.
        /// </summary>
        public static string WIZ_DB_UPDATING {
            get {
                return ResourceManager.GetString("WIZ_DB_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified login {0} already exists. Enter a different name..
        /// </summary>
        public static string WIZ_DB_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("WIZ_DB_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking existing database.
        /// </summary>
        public static string WIZ_DB_VALIDATION {
            get {
                return ResourceManager.GetString("WIZ_DB_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version required for work:.
        /// </summary>
        public static string WIZ_DB_VERSION_ACTUAL {
            get {
                return ResourceManager.GetString("WIZ_DB_VERSION_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the current database:.
        /// </summary>
        public static string WIZ_DB_VERSION_CURRENT {
            get {
                return ResourceManager.GetString("WIZ_DB_VERSION_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not contain [or].
        /// </summary>
        public static string WIZ_DB_WIZ_INVALID_PASSWORD_SYMBOLS {
            get {
                return ResourceManager.GetString("WIZ_DB_WIZ_INVALID_PASSWORD_SYMBOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open a connection to the database. Check the connection string..
        /// </summary>
        public static string WIZ_INVALID_CONNECTION_STRING {
            get {
                return ResourceManager.GetString("WIZ_INVALID_CONNECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect database or you do not have access..
        /// </summary>
        public static string WIZ_INVALID_DATABASE {
            get {
                return ResourceManager.GetString("WIZ_INVALID_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql.
        /// </summary>
        public static string WIZ_MYSQL {
            get {
                return ResourceManager.GetString("WIZ_MYSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Test connection.
        /// </summary>
        public static string WIZ_MYSQL_CHECK_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_CHECK_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string WIZ_MYSQL_CONNECTING {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to MySql.
        /// </summary>
        public static string WIZ_MYSQL_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create a new user.
        /// </summary>
        public static string WIZ_MYSQL_CREATE_NEW_USER {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_CREATE_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a user with administrative rights:.
        /// </summary>
        public static string WIZ_MYSQL_ENTER_ADMIN_USER_NAME {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_ENTER_ADMIN_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the port of the database server:.
        /// </summary>
        public static string WIZ_MYSQL_ENTER_PORT {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_ENTER_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the server:.
        /// </summary>
        public static string WIZ_MYSQL_ENTER_SERVER_NAME {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_ENTER_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SID of the database:.
        /// </summary>
        public static string WIZ_MYSQL_ENTER_SID {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_ENTER_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string WIZ_MYSQL_NEED_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_NEED_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string WIZ_MYSQL_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not specified.
        /// </summary>
        public static string WIZ_MYSQL_PASSWORD_IS_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_PASSWORD_IS_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database scheme.
        /// </summary>
        public static string WIZ_MYSQL_SELECT_SCHEME {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_SELECT_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the MySql server and specify connection parameters for the administrator.
        /// </summary>
        public static string WIZ_MYSQL_SELECT_SERVER {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_SELECT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the user settings that will be used to connect to the database.
        /// </summary>
        public static string WIZ_MYSQL_SELECT_USER_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_SELECT_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the name of the database schema: .
        /// </summary>
        public static string WIZ_MYSQL_SET_SCHEME_NAME {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_SET_SCHEME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User supplied parameters will be used for server connection and will be assigned to the selected database.
        /// </summary>
        public static string WIZ_MYSQL_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User name:.
        /// </summary>
        public static string WIZ_MYSQL_USER_NAME {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string WIZ_MYSQL_USER_NAME_LABEL {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_USER_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string WIZ_MYSQL_USER_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_MYSQL_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must back up the existing database.
        /// </summary>
        public static string WIZ_NEED_BACKUP {
            get {
                return ResourceManager.GetString("WIZ_NEED_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you upgrade the database, be sure to
        ///back up your existing version of the database..
        /// </summary>
        public static string WIZ_NEED_BACKUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_NEED_BACKUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you upgrade the database, be sure to
        ///back up your existing version of the database..
        /// </summary>
        public static string WIZ_NEED_BACKUP_MESSAGE {
            get {
                return ResourceManager.GetString("WIZ_NEED_BACKUP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard will create a new DB configuration.
        /// </summary>
        public static string WIZ_NEW_CONFIG_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_NEW_CONFIG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no list of rules that update the database. Download the rules by using the LoadRules method..
        /// </summary>
        public static string WIZ_NO_UPDATE_RULES {
            get {
                return ResourceManager.GetString("WIZ_NO_UPDATE_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT Security.
        /// </summary>
        public static string WIZ_NT_SECURITY {
            get {
                return ResourceManager.GetString("WIZ_NT_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        public static string WIZ_ORACLE {
            get {
                return ResourceManager.GetString("WIZ_ORACLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Test connection.
        /// </summary>
        public static string WIZ_ORACLE_CHECK_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_CHECK_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string WIZ_ORACLE_CONNECTING {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Oracle.
        /// </summary>
        public static string WIZ_ORACLE_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create a new user.
        /// </summary>
        public static string WIZ_ORACLE_CREATE_NEW_USER {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_CREATE_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a user with administrative rights:.
        /// </summary>
        public static string WIZ_ORACLE_ENTER_ADMIN_USER_NAME {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_ENTER_ADMIN_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the port of the database server:.
        /// </summary>
        public static string WIZ_ORACLE_ENTER_PORT {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_ENTER_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the server:.
        /// </summary>
        public static string WIZ_ORACLE_ENTER_SERVER_NAME {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_ENTER_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SID of the database:.
        /// </summary>
        public static string WIZ_ORACLE_ENTER_SID {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_ENTER_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string WIZ_ORACLE_NEED_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_NEED_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string WIZ_ORACLE_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not specified.
        /// </summary>
        public static string WIZ_ORACLE_PASSWORD_IS_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_PASSWORD_IS_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database scheme.
        /// </summary>
        public static string WIZ_ORACLE_SELECT_SCHEME {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_SELECT_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Oracle server and specify connection parameters for the administrator.
        /// </summary>
        public static string WIZ_ORACLE_SELECT_SERVER {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_SELECT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the user settings that will be used to connect to the database.
        /// </summary>
        public static string WIZ_ORACLE_SELECT_USER_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_SELECT_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the name of the database schema: .
        /// </summary>
        public static string WIZ_ORACLE_SET_SCHEME_NAME {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_SET_SCHEME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User supplied parameters will be used for server connection and will be assigned to the selected database.
        /// </summary>
        public static string WIZ_ORACLE_SETTINGS_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_SETTINGS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User name:.
        /// </summary>
        public static string WIZ_ORACLE_USER_NAME {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string WIZ_ORACLE_USER_NAME_LABEL {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_USER_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string WIZ_ORACLE_USER_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_ORACLE_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation settings.
        /// </summary>
        public static string WIZ_PARAMETER_CONFIRMATION {
            get {
                return ResourceManager.GetString("WIZ_PARAMETER_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos; {0} &apos; is not specified..
        /// </summary>
        public static string WIZ_PARAMETER_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("WIZ_PARAMETER_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing operation.
        /// </summary>
        public static string WIZ_PERFORMING_OPERATION {
            get {
                return ResourceManager.GetString("WIZ_PERFORMING_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product configuration.
        /// </summary>
        public static string WIZ_PRODUCT_CONFIGURATION {
            get {
                return ResourceManager.GetString("WIZ_PRODUCT_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider:.
        /// </summary>
        public static string WIZ_PROVIDER {
            get {
                return ResourceManager.GetString("WIZ_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select use an existing configuration..
        /// </summary>
        public static string WIZ_SELECT_CONFIG_USING_MODE {
            get {
                return ResourceManager.GetString("WIZ_SELECT_CONFIG_USING_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database.
        /// </summary>
        public static string WIZ_SELECT_DB_MESSAGE {
            get {
                return ResourceManager.GetString("WIZ_SELECT_DB_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the database provider.
        /// </summary>
        public static string WIZ_SELECT_DB_PROVIDER {
            get {
                return ResourceManager.GetString("WIZ_SELECT_DB_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Windows authentication for database server..
        /// </summary>
        public static string WIZ_SELECT_DB_WIN_AUTH_SERVER_CAPTION {
            get {
                return ResourceManager.GetString("WIZ_SELECT_DB_WIN_AUTH_SERVER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard successfully checked database availability for user &apos;{0}&apos;.
        ///If the configuration is made for a service running under a different account, 
        ///you may need to manually grant access to the database for the service account.
        ///.
        /// </summary>
        public static string WIZ_SELECT_DB_WIN_AUTH_SERVER_MESSAGE {
            get {
                return ResourceManager.GetString("WIZ_SELECT_DB_WIN_AUTH_SERVER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the &amp;database server.
        /// </summary>
        public static string WIZ_SELECT_SERVER_NAME {
            get {
                return ResourceManager.GetString("WIZ_SELECT_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode selection wizard.
        /// </summary>
        public static string WIZ_SELECT_WIZARD_MODE {
            get {
                return ResourceManager.GetString("WIZ_SELECT_WIZARD_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the Wizard mode  - create a new database or connect to existing database..
        /// </summary>
        public static string WIZ_SELECT_WIZARD_MODE_DESC1 {
            get {
                return ResourceManager.GetString("WIZ_SELECT_WIZARD_MODE_DESC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard will gather the necessary information, create a new database, initialize it and configure the product to use..
        /// </summary>
        public static string WIZ_SELECT_WIZARD_MODE_DESC2 {
            get {
                return ResourceManager.GetString("WIZ_SELECT_WIZARD_MODE_DESC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard allows you to configure the product to use an existing database..
        /// </summary>
        public static string WIZ_SELECT_WIZARD_MODE_DESC3 {
            get {
                return ResourceManager.GetString("WIZ_SELECT_WIZARD_MODE_DESC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select using mode of an existing configuration.
        /// </summary>
        public static string WIZ_SELECTING_CONFIGURATION_MODE {
            get {
                return ResourceManager.GetString("WIZ_SELECTING_CONFIGURATION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server:.
        /// </summary>
        public static string WIZ_SERVER_DB {
            get {
                return ResourceManager.GetString("WIZ_SERVER_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;SQL Server.
        /// </summary>
        public static string WIZ_SQL_AUTH {
            get {
                return ResourceManager.GetString("WIZ_SQL_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the authentication method.
        /// </summary>
        public static string WIZ_SQL_AUTH_MODE {
            get {
                return ResourceManager.GetString("WIZ_SQL_AUTH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to check permissions for &apos; {0} &apos;..
        /// </summary>
        public static string WIZ_SQL_CANNOT_VALIDATE_USER {
            get {
                return ResourceManager.GetString("WIZ_SQL_CANNOT_VALIDATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring administrative connection.
        /// </summary>
        public static string WIZ_SQL_CONFIGURING_ADMIIN_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_SQL_CONFIGURING_ADMIIN_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Server connection to DB.
        /// </summary>
        public static string WIZ_SQL_CONNECTION_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_SQL_CONNECTION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create a new login.
        /// </summary>
        public static string WIZ_SQL_CREATE_NEW_LOGIN {
            get {
                return ResourceManager.GetString("WIZ_SQL_CREATE_NEW_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Login:.
        /// </summary>
        public static string WIZ_SQL_LOGIN {
            get {
                return ResourceManager.GetString("WIZ_SQL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string WIZ_SQL_NEED_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_SQL_NEED_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Windows NT.
        /// </summary>
        public static string WIZ_SQL_NT_AUTH {
            get {
                return ResourceManager.GetString("WIZ_SQL_NT_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        public static string WIZ_SQL_PASSWORD {
            get {
                return ResourceManager.GetString("WIZ_SQL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co&amp;nfirm password:.
        /// </summary>
        public static string WIZ_SQL_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("WIZ_SQL_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh the list of servers.
        /// </summary>
        public static string WIZ_SQL_PRESS_FOR_UPDATING_SERVER_LIST {
            get {
                return ResourceManager.GetString("WIZ_SQL_PRESS_FOR_UPDATING_SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the authentication method for the administrative connection:.
        /// </summary>
        public static string WIZ_SQL_PROVIDE_AUTH_MODE {
            get {
                return ResourceManager.GetString("WIZ_SQL_PROVIDE_AUTH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the database connection settings.
        /// </summary>
        public static string WIZ_SQL_SELECT_DB_AND_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_SQL_SELECT_DB_AND_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the database name.
        /// </summary>
        public static string WIZ_SQL_SELECT_DB_NAME {
            get {
                return ResourceManager.GetString("WIZ_SQL_SELECT_DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select connection settings.
        /// </summary>
        public static string WIZ_SQL_SELECTING_CONNECTION_SETTINGS {
            get {
                return ResourceManager.GetString("WIZ_SQL_SELECTING_CONNECTION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL Server.
        /// </summary>
        public static string WIZ_SQL_SERVER {
            get {
                return ResourceManager.GetString("WIZ_SQL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of servers is updated ....
        /// </summary>
        public static string WIZ_SQL_SERVER_LIST_IS_UPDATING {
            get {
                return ResourceManager.GetString("WIZ_SQL_SERVER_LIST_IS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for servers ....
        /// </summary>
        public static string WIZ_SQL_SERVER_SEARCHING {
            get {
                return ResourceManager.GetString("WIZ_SQL_SERVER_SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the database server and its authentication.
        /// </summary>
        public static string WIZ_SQL_SET_SERVER_NAME_AND_AUTH_MODE {
            get {
                return ResourceManager.GetString("WIZ_SQL_SET_SERVER_NAME_AND_AUTH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Test connection.
        /// </summary>
        public static string WIZ_SQL_TEST_CONNECTION {
            get {
                return ResourceManager.GetString("WIZ_SQL_TEST_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure connection.
        /// </summary>
        public static string WIZ_SQL_USE_SSL {
            get {
                return ResourceManager.GetString("WIZ_SQL_USE_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected database provider ({0}) is not available. Select a different provider type..
        /// </summary>
        public static string WIZ_SRV_DB_PROVIDER_IS_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("WIZ_SRV_DB_PROVIDER_IS_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected user has no administrative rights that is required to create the database. Add the user to the Server sysadmin group..
        /// </summary>
        public static string WIZ_SRV_DB_USER_IS_NOT_ADMIN {
            get {
                return ResourceManager.GetString("WIZ_SRV_DB_USER_IS_NOT_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permissions.
        /// </summary>
        public static string WIZ_SRV_INVALID_DB_PERMISSIONS {
            get {
                return ResourceManager.GetString("WIZ_SRV_INVALID_DB_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}..
        /// </summary>
        public static string WIZ_SRV_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("WIZ_SRV_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the server has been successfully performed..
        /// </summary>
        public static string WIZ_SRV_LOGIN_SUCCEEDED {
            get {
                return ResourceManager.GetString("WIZ_SRV_LOGIN_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected user has no administrative rights that is required to create the database. Grant the user &apos;CREATE ANY DATABASE&apos; permission..
        /// </summary>
        public static string WIZ_SRV_NO_CREATE_DB_PERMISSION {
            get {
                return ResourceManager.GetString("WIZ_SRV_NO_CREATE_DB_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected user has no administrative rights that is required to create the SQL Server login. Grant the user &apos;ALTER ANY LOGIN&apos; permission..
        /// </summary>
        public static string WIZ_SRV_NO_CREATE_LOGIN_PERMISSION {
            get {
                return ResourceManager.GetString("WIZ_SRV_NO_CREATE_LOGIN_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Oracle Data Provider for .NET.
        ///It is either not installed or not properly configured..
        /// </summary>
        public static string WIZ_SRV_ORACLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("WIZ_SRV_ORACLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not specify a database server.
        /// </summary>
        public static string WIZ_SRV_SELECT {
            get {
                return ResourceManager.GetString("WIZ_SRV_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a secure SSL-connection..
        /// </summary>
        public static string WIZ_SRV_SSL_FAILED {
            get {
                return ResourceManager.GetString("WIZ_SRV_SSL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Windows user does not have administrative rights required to create the database. Add the user to the Server sysadmin group..
        /// </summary>
        public static string WIZ_SRV_WINDOWS_USER_IS_NOT_ADMIN {
            get {
                return ResourceManager.GetString("WIZ_SRV_WINDOWS_USER_IS_NOT_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database successfully upgrated to version {0}.
        /// </summary>
        public static string WIZ_SUCCESS_UPDATE {
            get {
                return ResourceManager.GetString("WIZ_SUCCESS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution progress:.
        /// </summary>
        public static string WIZ_UPDATING_PROGRESS {
            get {
                return ResourceManager.GetString("WIZ_UPDATING_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example usage:
        ///{0} [[[/&lt;key&gt;=&lt;value&gt;] /&lt;key&gt;=&lt;value&gt;] ...]
        ///
        ///&lt;key&gt;and &lt;value&gt;, where it is:
        ///	UnattendedMode-Specifies whether to run wizard in unattended mode. Its values: true, false. Default value: false. If false or omitted, then the deployment wizard will be initialized by the rest of the passed values. If true, the deployment wizard will be launched in unattended mode.
        ///
        ///DbProviderType-provider type in the database. Its values: {1}. default value: {2}
        ///
        ///Settings common to all providers of DB:
        ///
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WIZ_USAGE_MESSAGE_TEMPLATE {
            get {
                return ResourceManager.GetString("WIZ_USAGE_MESSAGE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an existing configuration.
        /// </summary>
        public static string WIZ_USING_EXISTING_CONFIG {
            get {
                return ResourceManager.GetString("WIZ_USING_EXISTING_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard will use an existing configuration to connect to DB.
        /// </summary>
        public static string WIZ_USING_EXISTING_CONFIG_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_USING_EXISTING_CONFIG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify parameters before performing an operation.
        /// </summary>
        public static string WIZ_VALIDATE_PARAMETERS {
            get {
                return ResourceManager.GetString("WIZ_VALIDATE_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation result.
        /// </summary>
        public static string WIZ_VALIDATION_RESULT {
            get {
                return ResourceManager.GetString("WIZ_VALIDATION_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result:.
        /// </summary>
        public static string WIZ_VALIDATION_RESULT2 {
            get {
                return ResourceManager.GetString("WIZ_VALIDATION_RESULT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while database updates.
        /// </summary>
        public static string WIZ_WAIT_UPDATING_COMPLETE {
            get {
                return ResourceManager.GetString("WIZ_WAIT_UPDATING_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the database connection mode.
        /// </summary>
        public static string WIZ_WIZARD_MODE_DESCRIPTION {
            get {
                return ResourceManager.GetString("WIZ_WIZARD_MODE_DESCRIPTION", resourceCulture);
            }
        }
    }
}
