//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.WizardFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.WizardFramework.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords that have been entered do not match.
        /// </summary>
        internal static string E_ITA_AGENT_PASSWORD_IS_DIFF {
            get {
                return ResourceManager.GetString("E_ITA_AGENT_PASSWORD_IS_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is too short. The password must be at least 6 characters length..
        /// </summary>
        internal static string E_ITA_AGENT_PASSWORD_IS_SHORT {
            get {
                return ResourceManager.GetString("E_ITA_AGENT_PASSWORD_IS_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard helps you to do all that is necessary to create DB configuration.
        /// </summary>
        internal static string I_ITA_ABOUT_MESSAGE {
            get {
                return ResourceManager.GetString("I_ITA_ABOUT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered directory does not exist.
        /// </summary>
        internal static string I_ITA_AGENT_DIRECTORY_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("I_ITA_AGENT_DIRECTORY_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Wizard - Wizard helps to save a backup copy of the master key for the database server..
        /// </summary>
        internal static string I_ITA_AGENT_MK_EXPORT_INFO {
            get {
                return ResourceManager.GetString("I_ITA_AGENT_MK_EXPORT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Export Wizard for master DB key.
        /// </summary>
        internal static string I_ITA_AGENT_MK_EXPORT_WELCOME {
            get {
                return ResourceManager.GetString("I_ITA_AGENT_MK_EXPORT_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a file name or select it using the Browse button.
        /// </summary>
        internal static string I_ITA_AGENT_SELECT_FILE {
            get {
                return ResourceManager.GetString("I_ITA_AGENT_SELECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        internal static string I_ITA_AGENT_THANKS {
            get {
                return ResourceManager.GetString("I_ITA_AGENT_THANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the wizard?.
        /// </summary>
        internal static string I_ITA_ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("I_ITA_ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; &amp;Back.
        /// </summary>
        internal static string I_ITA_BACK {
            get {
                return ResourceManager.GetString("I_ITA_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string I_ITA_CANCEL {
            get {
                return ResourceManager.GetString("I_ITA_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string I_ITA_CAPTION {
            get {
                return ResourceManager.GetString("I_ITA_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Complete to close the wizard..
        /// </summary>
        internal static string I_ITA_CLICK_CLOSE {
            get {
                return ResourceManager.GetString("I_ITA_CLICK_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully completed all necessary steps in the wizard..
        /// </summary>
        internal static string I_ITA_COMPLETE_MESSAGE {
            get {
                return ResourceManager.GetString("I_ITA_COMPLETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue, click Next..
        /// </summary>
        internal static string I_ITA_CONTINUE_MESSAGE {
            get {
                return ResourceManager.GetString("I_ITA_CONTINUE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Complete.
        /// </summary>
        internal static string I_ITA_FINISH {
            get {
                return ResourceManager.GetString("I_ITA_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next &gt;.
        /// </summary>
        internal static string I_ITA_NEXT {
            get {
                return ResourceManager.GetString("I_ITA_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using the wizard.
        /// </summary>
        internal static string I_ITA_THANKYOU_MESSAGE {
            get {
                return ResourceManager.GetString("I_ITA_THANKYOU_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Setup Wizard.
        /// </summary>
        internal static string I_ITA_WELCOME_MESSAGE {
            get {
                return ResourceManager.GetString("I_ITA_WELCOME_MESSAGE", resourceCulture);
            }
        }
    }
}
