//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITA.Common.Passwords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordQualityMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordQualityMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITA.Common.Passwords.PasswordQualityMessages", typeof(PasswordQualityMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be at least {0} alpha symbol(s)..
        /// </summary>
        internal static string ALPHA_NOT_LESS_THAN {
            get {
                return ResourceManager.GetString("ALPHA_NOT_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be only ASCII symbols..
        /// </summary>
        internal static string ASCII_ONLY {
            get {
                return ResourceManager.GetString("ASCII_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quality parameters..
        /// </summary>
        internal static string E_INVALID_QUALITY_PARAMS {
            get {
                return ResourceManager.GetString("E_INVALID_QUALITY_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length should be at least {0} symbol(s)..
        /// </summary>
        internal static string LENGTH_NOT_LESS_THAN {
            get {
                return ResourceManager.GetString("LENGTH_NOT_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length should be maximum {0} symbol(s)..
        /// </summary>
        internal static string LENGTH_NOT_MORE_THAN {
            get {
                return ResourceManager.GetString("LENGTH_NOT_MORE_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be at least {0} lowercase symbol(s)..
        /// </summary>
        internal static string LOWER_NOT_LESS_THAN {
            get {
                return ResourceManager.GetString("LOWER_NOT_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be alpha symbols..
        /// </summary>
        internal static string NO_ALPHA {
            get {
                return ResourceManager.GetString("NO_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be lowercase symbols..
        /// </summary>
        internal static string NO_LOWER {
            get {
                return ResourceManager.GetString("NO_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be numeric symbols..
        /// </summary>
        internal static string NO_NUMBER {
            get {
                return ResourceManager.GetString("NO_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be special symbols..
        /// </summary>
        internal static string NO_SPECIAL {
            get {
                return ResourceManager.GetString("NO_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be uppercase symbols..
        /// </summary>
        internal static string NO_UPPER {
            get {
                return ResourceManager.GetString("NO_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be at least {0} numeric symbol(s)..
        /// </summary>
        internal static string NUMBER_NOT_LESS_THAN {
            get {
                return ResourceManager.GetString("NUMBER_NOT_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be maximum {0} symbol repetitions in row..
        /// </summary>
        internal static string REPEATED_NOT_MORE_THAN {
            get {
                return ResourceManager.GetString("REPEATED_NOT_MORE_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be at least {0} special symbol(s)..
        /// </summary>
        internal static string SPECIAL_NOT_LESS_THAN {
            get {
                return ResourceManager.GetString("SPECIAL_NOT_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be at least {0} uppercase symbol(s)..
        /// </summary>
        internal static string UPPER_NOT_LESS_THAN {
            get {
                return ResourceManager.GetString("UPPER_NOT_LESS_THAN", resourceCulture);
            }
        }
    }
}
